name: Deploy Vue.js App to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti dengan nama branch utama Anda jika berbeda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Pastikan versi Node.js sesuai dengan proyek Anda

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_API_KEY: ${{ secrets.API_KEY }}  # Mengambil API key dari GitHub Secrets
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Sesuaikan dengan direktori hasil build Anda
